### ISSUE TITLE
Seems to be an upcoming conflict with LiipImagineBundle

### ISSUE THREAD

**Issue by bastien70** [Lustmored/flysystem-v2-simple-cache-adapter#2] opened 2022-01-19 11:09 UTC
Hello, according these two issues in LiipImagineBundle : 

https://github.com/liip/LiipImagineBundle/issues/1261
https://github.com/liip/LiipImagineBundle/issues/1442

We have to pass the **liip_imagine.twig.mode** to `lazy`
I wonder what will change on our side with this bundle?

The fact is that when going into lazy mode, **liip_imagine** just doesn't work anymore (see https://github.com/liip/LiipImagineBundle/issues/1447), and I wonder if it could be from this bundle.

What do you think ?

**Comment by Lustmored** [comment] 2022-01-19 11:15
Hi,

Thank you for reporting the issue. I am not personally using LiipImagineBundle, so could you please elaborate a bit about what the problem is on our side and, if possible, provide an example test case? That would speed things up a lot on my side :)

**Comment by bastien70** [comment] 2022-01-19 12:27
Hi, I am creating a project to put all of this as an example.

It will contain the combo:

Flysystem
AWS
LiipImagine
As well as your bundle

To make the installation quick on your end, I will configure the AWS bucket myself if you wish.

The github repository will be posted here, along with my explanations.
Nevertheless, I would like to have your email address to send you the AWS identifiers soon, so that you are the only one who can benefit from them with me, so that these remain a minimum of secrets

**Comment by Lustmored** [comment] 2022-01-19 12:41
@bastien70 if you're hiding AWS operator behind cache there should be no differences between running it with AWS and local adapter, so hopefully there won't be need for AWS operations at all. But if it does - I will manage at my own as I'm using S3 pretty much everywhere, so no need to send sensitive access tokens :+1: 

Also - I will be able to look at it this Friday the soonest :+1:

**Comment by bastien70** [comment] 2022-01-19 13:09
Ok just an update to say that your bundle has nothing to do with it. Even without it, liip_imagine can no longer handle images with their future update. So I will have to see with them

**Comment by Lustmored** [comment] 2022-01-19 13:12
@bastien70 Thanks for the info. I will close the issue now. If the problem bounces back feel free to reopen it :smiley:

**Closed as completed by Lustmored** 2022-01-19 13:12 UTC
